model_dir: /home/vsatish/Data/dexnet/data/models/grasp_quality
output_dir: /home/vsatish/Data/dexnet/data/analyses/gqcnn_training_performance

out_rate: 1
font_size: 15
dpi: 100

models:
  model_aedbmlhhrg :
    tag: GQCNN (N=100)
    type: gqcnn
    batch_size: 64
    im_height: 32
    im_width: 32
    im_channels: 1
    input_data_mode: tf_image
    replace: 0
    vis_conv: 0
