language: python

matrix:
  include:
    - name: "Python 2.7 on Trusty Linux"
      python: 2.7
      dist: trusty
      
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial

    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial

    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install python-opengl

install: 
  - pip install .

script:
  - python --version && python -c "import gqcnn"
