# general experiment parameters		
planner_type: gqcnn_2d
trials_per_object: 5
supervisor: jeff
human_reset: 1
query_human: 1
datapoints_per_file: 1000
gripper: yumi_metal_spline
table_to_world_z_offset: -0.0025

test_object_keys:
  - bar_clamp
  - gearbox
  - nozzle
  - part1
  - part3
  - pawn
  - turbine_housing
  - vase

planning:
  num_grasp_samples: 100
  policy: max

  gqcnn_model: /mnt/hdd/dex-net/data/models/grasp_quality/gqcnn_mini_dexnet_all_trans_depth_gp_high_noise_11_19_16

  tf:
    batch_size: 64
    im_height: 32
    im_width: 32
    im_channels: 1
    pose_dim: 1
    pool_size: 2
    pool_stride: 1

  min_phi: -45
  max_phi: 45
  min_psi: -45
  max_psi: 45

  platform_z: -0.0019
  table_offset: 0.02

  crop_dim: 64
  depth_sample_win_height: 4
  depth_sample_win_width: 4
  depth_sample_offset: 0.005
  max_depth: 0.70
  depth_inc: 0.005

  friction_coef: 0.6
  grasp_width_px: 27
  angle_perturbation_mag: 0
  center_sigma: 0
  grad_norm_pctile: 97
  min_grad_norm: 0.002

# filtering params
filtering:
  color_median_win_size: 5
  color_bilateral_win_size: 7
  color_bilateral_range_sigma: 5.0
  color_bilateral_spatial_sigma: 2.5
  depth_median_win_size: 5
  depth_bilateral_win_size: 5
  depth_bilateral_range_sigma: 0.005
  depth_bilateral_spatial_sigma: 2.0  

# database params
database_dir: &id_database_dir /mnt/hdd/dex-net/data/db
database_cache_dir: *id_database_dir
database_name: yumi_mini_dexnet_autolab2.hdf5
database_access_level: READ_ONLY
dataset_name: mini_dexnet

# sensor params
calib_dir: /home/autolab/Public/alan/calib
num_depth_images: 3
sensor:
  device_num: 0
  frame: kinect2_overhead
  pipeline_mode: 0

# control params
control:
  use_left: 1
  approach_velocity: 200
  approach_zoning: z50
  standard_velocity: 500
  standard_zoning: fine

# grasping params
grasping:
  lift_height: 0.1
  align_lift_vertically: 1
  min_gripper_depth: 0.0125
  lift_detector_num_points: 150
  pickup_min_width: 0.0001

  max_attempts: 100

  approach_dist: 0.075
  delta_approach: 0.005
  
  approach_angle:
    min_deg: -10
    max_deg: -80
    table_deg: 20

  target_metric: robust_ferrari_canny
  metric_threshold: 0.0001

  grasp_ids_filename: experiment_grasps_ids.json
  grasp_info_filename: grasp_info.pkl

# registration params
registration:
  crop_center_px:
    - 200
    - 210
  crop_dim:
    - 200
    - 200

  depth_im_median_filter_dim: 5
  depth_im_erosion_filter_dim: 3
  depth_im_close_filter_dim: 3
  binary_im_close_filter_dim: 3
  depth_im_grad_thresh: 0.015
  depth_im_rescale_factor: 1.0
  contour_dist_thresh: 2.5
  foreground_mask_tolerance: 30
  index_im_dim: 150
  area_thresh: 200
  cache_im_filename: data/caffe/cnn_grayscale_im.jpg

  num_nearest_neighbors: 3

  single_stage: 0

  segment_kmeans: 1
  color_seg_num_clusters: 2
  color_seg_rgb_weight: 1.5
  color_seg_hsv_weight: 5.0
  color_seg_dist_pctile: 5.0
  color_seg_dist_thresh: 30.0
  color_seg_min_bg_dist: 275.0

  icp_sample_size: 250
  icp_cost_eval_sample_size: 1000
  icp_relative_point_plane_cost: 100
  icp_regularization_lambda: 0.01
  feature_matcher_dist_thresh: 0.025
  feature_matcher_norm_thresh: 0.75
  num_registration_iters: 10
  compute_total_registration_cost: 1
  early_term_cost: 0.028
  threshold_cost: 0.038
  align_stable_pose: 1

  workspace_min_pt:
    - 0.13
    - -0.25
    - 0.01
  workspace_max_pt:
    - 0.5
    - 0.25
    - 0.25

# tensorflow params for classification
tf:
  batch_size: 64
  im_width: 227
  im_height: 227
  channels: 3
  out_layer: conv5
  feature_layer: conv5
  out_size: 10
  caffe_weights: data/cnn/bvlc_alexnet.npy
  mean_file: /mnt/hdd/dex-net/data/models/cnn/mini_dexnet_classifier_11_13_16/mean.npy
  use_stable_poses: 1
  image_type: color
  cache_file: data/cnn/tables_mini_dexnet.pkl
  model_dir: /mnt/hdd/dex-net/data/models/cnn/mini_dexnet_classifier_11_13_16

# classifier params
classifier:
  model_dir: /mnt/hdd/dex-net/data/models/nn_cnn_two_stage_09_06_16

# visualization params
vis:
  raw: 0
  input: 0
  tf_images: 0
  plan: 0
  predictions: 0
  debug_registration: 0
  final_registration: 0
  k: 5

# debugging
debug: 0
robot_off: 0
