# grasping params
inpaint_rescale_factor: 0.5

# sensor params
calib_dir: /home/autolab/Public/alan/calib
sensor:
  type: virtual_primesense
  frame: primesense_overhead
  auto_white_balance: 0
  image_dir: /home/autolab/Public/data/dex-net/data/gqcnn/test/detection_001

# policy params
policy:
  num_grasp_samples: 100
  gripper_width: 0.05
  crop_height: 96
  crop_width: 96

  # gqcnn params
  gqcnn_model: /home/autolab/Public/data/dex-net/data/models/grasp_quality/gqcnn_test_network
  
  # sampling params
  sampling:
    # type
    type: antipodal_depth

    # antipodality
    friction_coef: 0.8
    depth_grad_thresh: 0.005
    depth_grad_gaussian_sigma: 1.0
    downsample_rate: 4
    max_num_attempts: 1000

    # distance
    max_dist_from_center: 120
    min_grasp_dist: 0.025
    angle_dist_weight: 0.025

    # depth sampling
    depth_samples_per_grasp: 1
    depth_sample_win_height: 1
    depth_sample_win_width: 1
    min_depth_offset: 0.015
    max_depth: 0.69

  # visualization
  vis:
    sampling : 0
    tf: 0
    candidates: 0
    plan: 0
